

currentPasswordInPropFile=Password2
newPasswordInPropFile=Password1_09Mar26
confirmPasswordInPropFile=Password1_09Mar26

eventidKey=9000477138
eventtitleInPropFile =automation
dateInPropFile=01/01/2040
venueNameInPropFile=Professional colony
venueAddressInPropFile=Indore
clientnameInPropFile=VonageVideoPresenterBridge
FirstnameInPropFile=Bhushan
LastnameInPropFile=Mahire
EmailInPropFile=bhushan.mahire48@gmail.com
CompanyInPropFile=Lms
InPropFile_Attendee_Type=In-Person


#==================================eu =================

Newtemp_type_forums_user=forumpeg
Newtemp_type_forums_password=Password1_24Dec25
Newtemp_type_presenter_user=PresenterLoginNA
Newtemp_type_presenter_password=Password1_24Dec25
elite.react.automation.elite.editpermissionone.user=editpermissionone
elite.react.automation.elite.editpermissionone.password=Password1_05Jan26

# ================== URL ==================
url=https://wcc.on24.com/webcast/login
# ================== COMMON LOGIN ==================
usernameKeyInPropFile =aypl
passwordKeyInPropFile=Password1

# ================== DIFFERENT LOGINS ==================
user1.username=user1@example.com
user1.password=Password@123

user2.username=user2@example.com
user2.password=Password@456

user3.username=user3@example.com
user3.password=Password@789


# ================== CLIENT NAMES ==================
client1=Accenture
client2=AutoEEP AjayBothoff
client3=AutoEEP AjayFM
client4=AutoEEP AjayFOnly
client5=AutoEEP AjayMOnly
client6=Calander Invite
client7=defaultarchive
client8=doubleOptInAllCountries
client9=doubleOptInSelectCountries
client10=doubleOptInThankyouURL


# ================== PASSWORD RESET ==================
currentPassword=Password@123
newPassword=NewPassword@123
confirmPassword=NewPassword@123